#!/usr/bin/env python3
"""Generate per-library nginx location blocks from config.LIBRARIES.

Writes an nginx config file with one ``location`` block per configured
library root, so that nginx enforces path scoping at the web-server level
in addition to the server-side validation in the Python backend.

Called by the container init script before nginx starts.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from a checkout where backend is not on sys.path.
_BACKEND_DIR = Path(__file__).resolve().parent.parent / "backend"
sys.path.insert(0, str(_BACKEND_DIR))

from config import DEV_MODE  # noqa: E402
from config.config_manager import config_manager as cm  # noqa: E402

OUTPUT_PATH = "/etc/nginx/conf.d/libraries.conf"


def generate_nginx_config() -> str:
    """Return nginx location blocks for each configured library."""
    libraries = cm.get_config().LIBRARIES
    lines: list[str] = [
        "# Auto-generated by scripts/generate_nginx_library_config.py",
        "# Do not edit manually — regenerate by restarting the container.",
        "",
    ]

    for lib in libraries:
        lib_id = lib["id"]
        lib_path = lib["path"]
        # Ensure trailing slash for nginx alias
        alias_path = lib_path if lib_path.endswith("/") else f"{lib_path}/"
        lines.extend(
            [
                f"location /library/{lib_id}/ {{",
                "    internal;",
                f'    alias "{alias_path}";',
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> int:
    if DEV_MODE:
        print("DEV_MODE=true — skipping nginx config generation")
        return 0

    config_text = generate_nginx_config()
    print(f"Writing library nginx config to {OUTPUT_PATH}")
    print(config_text)

    output = Path(OUTPUT_PATH)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(config_text)

    print(f"\nGenerated {len(cm.get_config().LIBRARIES)} library location block(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
